Update test-install.yaml

diff --git a/.github/workflows/test-install.yaml b/.github/workflows/test-install.yaml
--- a/.github/workflows/test-install.yaml
+++ b/.github/workflows/test-install.yaml
@@ -5,11 +5,16 @@ on:
     branches:
       - main
   pull_request:
+      
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 
 jobs:
   test-install:
     runs-on: ${{ matrix.os }}
     strategy:
+      fail-fast: false
       matrix:
         os: [ubuntu-latest, windows-latest, macos-latest]
         python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
@@ -22,10 +27,13 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
 
-      - name: Upgrade pip
-        run: python -m pip install --upgrade pip
+      - name: Upgrade pip and install uv
+        run: |
+          python -m pip install --upgrade pip
+          python -m pip install uv
 
       - name: Install Poetry (for poetry install test)
+        if: ${{ matrix.os != 'windows-latest' }}
         run: pip install poetry
         shell: bash
 
@@ -46,12 +54,14 @@ jobs:
         run: python -c "import multicall"
 
       - name: poetry install
+        if: ${{ matrix.os != 'windows-latest' }}
         run: |
           poetry config virtualenvs.create false
           poetry install
         shell: bash
         
       - name: Test import after poetry install
+        if: ${{ matrix.os != 'windows-latest' }}
         run: python -c "import multicall"
 
       - name: Build Wheel and Install
@@ -71,3 +81,13 @@ jobs:
 
       - name: Test import after pip install with extras [dev]
         run: python -c "import multicall"
+
+      - name: Test uninstall package if already installed
+        run: python -m pip uninstall -y multicall || echo "Ignore uninstall failure"
+
+      - name: Test install with uv (from PyPI)
+        run: uv multicall
+
+      - name: Test import after uv install
+        run: python -c "import multicall"
+        
